// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkBD6eIMHOOcfj_XNy1ZIcZBOMJLTm9kM',
    appId: '1:1051237960882:web:0c95a7af2615306a198dab',
    messagingSenderId: '1051237960882',
    projectId: 'flutter-firebase-f504e',
    authDomain: 'flutter-firebase-f504e.firebaseapp.com',
    storageBucket: 'flutter-firebase-f504e.appspot.com',
    measurementId: 'G-TM93CJHL1H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFt9XLezl9rCwFPFviyG1--qkLOaTfobo',
    appId: '1:1051237960882:android:f3db351df485f77f198dab',
    messagingSenderId: '1051237960882',
    projectId: 'flutter-firebase-f504e',
    storageBucket: 'flutter-firebase-f504e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCra6fEhsZf5oB67jJfF4bLKCo-KqgBr1w',
    appId: '1:1051237960882:ios:1114102f615bff6e198dab',
    messagingSenderId: '1051237960882',
    projectId: 'flutter-firebase-f504e',
    storageBucket: 'flutter-firebase-f504e.appspot.com',
    iosClientId: '1051237960882-r6ulbhsrjr6qh93bpde3q70a6ntijaom.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );
}
